"""context.yaml loader and renderer for SpringInsight.

The context.yaml captures everything agents need to know about a project:
tech stack, module structure, custom rules, exclusions, etc.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

CONTEXT_FILENAME = "context.yaml"
CONTEXT_TEMPLATE = """\
# SpringInsight Project Context
# Generated by: springinsight init
# Edit this file to customize agent behavior for your project.

project:
  name: "{name}"
  description: "{description}"
  base_path: "{base_path}"

tech_stack:
  java_version: {java_version}
  spring_boot_version: "{spring_boot_version}"
  build_tool: {build_tool}            # maven | gradle
  database: {database}               # mysql | postgresql | oracle | mongodb | h2
  orm: {orm}                         # hibernate | mybatis | none
  messaging: {messaging}             # rabbitmq | kafka | activemq | none
  cache: {cache}                     # redis | hazelcast | caffeine | none
  auth: {auth}                       # jwt | oauth2 | keycloak | session | basic
  api_type: {api_type}               # rest | graphql | grpc | mixed

structure:
  modules:
{modules_yaml}

patterns:
  multi_tenancy: {multi_tenancy}
  tenant_filter_class: "{tenant_filter_class}"
  base_entity: "{base_entity}"
  custom_rules:
{custom_rules_yaml}

exclusions:
  packages:
    - "*.generated.*"
    - "*.test.*"
  paths:
    - "*/target/*"
    - "*/build/*"
    - "*/.git/*"
    - "*/node_modules/*"

agents:
  enabled: all                       # all | [A03, A10, A12, ...]
  parallelism: 6                     # max concurrent agents
  output_dir: ".springinsight/runs"
"""


@dataclass
class ModuleInfo:
    name: str
    path: str
    role: str = ""


@dataclass
class ProjectContext:
    # Project basics
    name: str = "My Spring Boot Project"
    description: str = ""
    base_path: str = ""

    # Tech stack
    java_version: int = 17
    spring_boot_version: str = "3.2.x"
    build_tool: str = "maven"
    database: str = "mysql"
    orm: str = "hibernate"
    messaging: str = "none"
    cache: str = "none"
    auth: str = "jwt"
    api_type: str = "rest"

    # Module structure
    modules: list[ModuleInfo] = field(default_factory=list)

    # Patterns
    multi_tenancy: bool = False
    tenant_filter_class: str = ""
    base_entity: str = ""
    custom_rules: list[str] = field(default_factory=list)

    # Exclusions
    exclude_packages: list[str] = field(default_factory=lambda: ["*.generated.*", "*.test.*"])
    exclude_paths: list[str] = field(default_factory=lambda: ["*/target/*", "*/build/*"])

    # Agent config
    enabled_agents: str = "all"
    parallelism: int = 6
    output_dir: str = ".springinsight/runs"

    # Raw parsed data for anything not explicitly modelled
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


def detect_spring_boot_version(project_path: Path) -> str | None:
    """Auto-detect Spring Boot version from pom.xml, build.gradle, or build.gradle.kts.

    Returns version string like "3.5.0" or "4.0.0", or None if undetectable.
    """
    # ── pom.xml ──────────────────────────────────────────────────────────────
    for pom in [project_path / "pom.xml", *project_path.glob("*/pom.xml")]:
        if pom.exists():
            try:
                content = pom.read_text(encoding="utf-8", errors="ignore")
                # Most common: spring-boot-starter-parent in <parent>
                m = re.search(
                    r"spring-boot-starter-parent.*?<version>\s*([0-9]+\.[0-9]+[^<]+)</version>",
                    content, re.DOTALL | re.IGNORECASE,
                )
                if m:
                    return m.group(1).strip()
                # Fallback: spring.boot.version property
                m = re.search(
                    r"<spring[-.]boot\.version>\s*([0-9]+\.[0-9]+[^<]+)</spring",
                    content, re.IGNORECASE,
                )
                if m:
                    return m.group(1).strip()
            except Exception:
                pass

    # ── build.gradle / build.gradle.kts ──────────────────────────────────────
    for gradle in [
        project_path / "build.gradle",
        project_path / "build.gradle.kts",
        *project_path.glob("*/build.gradle"),
    ]:
        if gradle.exists():
            try:
                content = gradle.read_text(encoding="utf-8", errors="ignore")
                # Plugins DSL: id 'org.springframework.boot' version '3.5.0'
                m = re.search(
                    r"""id\s*['"(]org\.springframework\.boot['"]\)?\s+version\s+['"]([0-9]+\.[0-9]+[^'"]+)['"]""",
                    content,
                )
                if m:
                    return m.group(1).strip()
                # Legacy: springBootVersion = '3.5.0'
                m = re.search(r"springBootVersion\s*=\s*['\"]([0-9]+\.[0-9]+[^'\"]+)['\"]", content)
                if m:
                    return m.group(1).strip()
            except Exception:
                pass

    return None


def get_spring_boot_version_notes(version: str) -> str:
    """Return version-specific guidance to inject into the agent context block."""
    if not version:
        return ""

    major, minor = 3, 2
    try:
        parts = version.split(".")
        major = int(parts[0])
        minor = int(parts[1])
    except Exception:
        pass

    notes: list[str] = []

    if major >= 4:
        notes += [
            "⚠  Spring Boot 4.0: Jakarta EE 11, Spring Framework 7, Java 17+ required.",
            "   @RequestMapping on interface default methods is now deprecated.",
            "   HttpClient bean replaced with RestClient by default.",
            "   spring-boot-parent no longer published — use BOM directly.",
            "   Migrate from spring.factories to @AutoConfiguration.",
        ]
    elif major == 3:
        if minor >= 5:
            notes += [
                "ℹ  Spring Boot 3.5: Structured logging (ECS/GELF/Logstash), WebClient builder API.",
                "   heapdump actuator defaults to access=NONE — verify your config.",
                "   TaskExecutor bean: use 'applicationTaskExecutor' name (not 'taskExecutor').",
                "   Property validation: .enabled keys must be true/false only.",
                "   Apache Pulsar upgraded to 4.0.x.",
            ]
        elif minor >= 4:
            notes += [
                "ℹ  Spring Boot 3.4: Virtual threads stable (Java 21+), RestClient GA.",
                "   Micrometer 1.14, Spring Security 6.4.",
                "   @ServiceConnection expanded to more connection types.",
            ]
        elif minor >= 3:
            notes += [
                "ℹ  Spring Boot 3.3: CDS (Class Data Sharing) support, @ConditionalOnThreading.",
                "   Micrometer 1.13, Flyway 10+.",
            ]
        elif minor >= 2:
            notes += [
                "ℹ  Spring Boot 3.2: Virtual threads preview, RestClient introduced.",
                "   spring.threads.virtual.enabled=true to enable Loom.",
            ]
        elif minor <= 1:
            notes += [
                "⚠  Spring Boot 3.0/3.1 is reaching end-of-support. Recommend upgrade to 3.5.x.",
            ]

    if not notes:
        return ""
    return "Spring Boot Version Notes:\n" + "\n".join(f"  {n}" for n in notes)


def load_context(work_dir: Path) -> ProjectContext:
    """Load context.yaml from work_dir. Returns defaults if file not found."""
    ctx_path = work_dir / CONTEXT_FILENAME
    if not ctx_path.exists():
        # No context.yaml — try to auto-detect the Spring Boot version
        ctx = ProjectContext()
        detected_version = detect_spring_boot_version(work_dir)
        if detected_version:
            ctx.spring_boot_version = detected_version
        return ctx

    raw = yaml.safe_load(ctx_path.read_text(encoding="utf-8")) or {}
    ctx = ProjectContext(_raw=raw)

    proj = raw.get("project", {})
    ctx.name = proj.get("name", ctx.name)
    ctx.description = proj.get("description", ctx.description)
    ctx.base_path = proj.get("base_path", ctx.base_path)

    tech = raw.get("tech_stack", {})
    ctx.java_version = tech.get("java_version", ctx.java_version)
    ctx.spring_boot_version = tech.get("spring_boot_version", ctx.spring_boot_version)
    # If the context.yaml still has the template default, try auto-detect
    if ctx.spring_boot_version in ("3.2.x", "3.x.x", "", None):
        detected = detect_spring_boot_version(work_dir)
        if detected:
            ctx.spring_boot_version = detected
    ctx.build_tool = tech.get("build_tool", ctx.build_tool)
    ctx.database = tech.get("database", ctx.database)
    ctx.orm = tech.get("orm", ctx.orm)
    ctx.messaging = tech.get("messaging", ctx.messaging)
    ctx.cache = tech.get("cache", ctx.cache)
    ctx.auth = tech.get("auth", ctx.auth)
    ctx.api_type = tech.get("api_type", ctx.api_type)

    struct = raw.get("structure", {})
    for mod in struct.get("modules", []):
        ctx.modules.append(ModuleInfo(
            name=mod.get("name", ""),
            path=mod.get("path", ""),
            role=mod.get("role", ""),
        ))

    patterns = raw.get("patterns", {})
    ctx.multi_tenancy = patterns.get("multi_tenancy", ctx.multi_tenancy)
    ctx.tenant_filter_class = patterns.get("tenant_filter_class", ctx.tenant_filter_class)
    ctx.base_entity = patterns.get("base_entity", ctx.base_entity)
    ctx.custom_rules = patterns.get("custom_rules", ctx.custom_rules)

    excl = raw.get("exclusions", {})
    ctx.exclude_packages = excl.get("packages", ctx.exclude_packages)
    ctx.exclude_paths = excl.get("paths", ctx.exclude_paths)

    agents_cfg = raw.get("agents", {})
    ctx.enabled_agents = agents_cfg.get("enabled", ctx.enabled_agents)
    ctx.parallelism = agents_cfg.get("parallelism", ctx.parallelism)
    ctx.output_dir = agents_cfg.get("output_dir", ctx.output_dir)

    return ctx


def render_context_block(ctx: ProjectContext, project_path: str) -> str:
    """Render the context block injected into every agent's prompt."""
    modules_text = ""
    if ctx.modules:
        for m in ctx.modules:
            modules_text += f"  - {m.name}: {m.path}"
            if m.role:
                modules_text += f" ({m.role})"
            modules_text += "\n"
    else:
        modules_text = "  (single-module project)\n"

    custom_rules_text = ""
    if ctx.custom_rules:
        for r in ctx.custom_rules:
            custom_rules_text += f"  - {r}\n"
    else:
        custom_rules_text = "  (none specified)\n"

    version_notes = get_spring_boot_version_notes(ctx.spring_boot_version)

    return f"""
╔══════════════════════════════════════════════════════════════════╗
║                    PROJECT CONTEXT                                ║
╚══════════════════════════════════════════════════════════════════╝
Project Name    : {ctx.name}
Description     : {ctx.description}
Project Path    : {project_path}
Java Version    : {ctx.java_version}
Spring Boot     : {ctx.spring_boot_version}
Build Tool      : {ctx.build_tool}
Database        : {ctx.database}  (ORM: {ctx.orm})
Auth            : {ctx.auth}
Cache           : {ctx.cache}
Messaging       : {ctx.messaging}
API Type        : {ctx.api_type}
Multi-Tenancy   : {"YES — " + ctx.tenant_filter_class + " / " + ctx.base_entity if ctx.multi_tenancy else "NO"}

Modules:
{modules_text}
Custom Rules (MUST APPLY):
{custom_rules_text}
{version_notes + chr(10) if version_notes else ""}Excluded from analysis:
  paths : {", ".join(ctx.exclude_paths)}
  packages: {", ".join(ctx.exclude_packages)}
╚══════════════════════════════════════════════════════════════════╝
""".strip()


def save_context(ctx: ProjectContext, work_dir: Path) -> Path:
    """Serialize ProjectContext back to context.yaml."""
    modules_yaml = ""
    for m in ctx.modules:
        modules_yaml += f'    - name: "{m.name}"\n'
        modules_yaml += f'      path: "{m.path}"\n'
        if m.role:
            modules_yaml += f'      role: "{m.role}"\n'

    custom_rules_yaml = ""
    for r in ctx.custom_rules:
        custom_rules_yaml += f'    - "{r}"\n'
    if not custom_rules_yaml:
        custom_rules_yaml = "    []\n"

    content = CONTEXT_TEMPLATE.format(
        name=ctx.name,
        description=ctx.description,
        base_path=ctx.base_path,
        java_version=ctx.java_version,
        spring_boot_version=ctx.spring_boot_version,
        build_tool=ctx.build_tool,
        database=ctx.database,
        orm=ctx.orm,
        messaging=ctx.messaging,
        cache=ctx.cache,
        auth=ctx.auth,
        api_type=ctx.api_type,
        modules_yaml=modules_yaml if modules_yaml else "    []\n",
        multi_tenancy=str(ctx.multi_tenancy).lower(),
        tenant_filter_class=ctx.tenant_filter_class,
        base_entity=ctx.base_entity,
        custom_rules_yaml=custom_rules_yaml,
    )

    ctx_path = work_dir / CONTEXT_FILENAME
    ctx_path.write_text(content, encoding="utf-8")
    return ctx_path
